// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sbfiqzvppqqqpqlqodlk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNiZmlxenZwcHFxcXBxbHFvZGxrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg2NjQwODUsImV4cCI6MjA4NDI0MDA4NX0.QSNp2jc0TN83MJESSlxUvyT8N_Eix_eAAc7JOY3pIAo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});